meta_product_name: "SpeedrunTheWeb"
meta_title: "SpeedrunTheWeb - The Wikipedia Game"
meta_description: "SpeedRunTheWeb is a fun and interactive way to learn new topics all while "
meta_image: "cover.png" # should exist in `app/assets/images/`
